// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AxesHelper: typeof import('./src/helpers/AxesHelper.ts')['default']
    BoxGeometry: typeof import('./src/geometries/BoxGeometry.ts')['default']
    Camera: typeof import('./src/cameras/Camera.ts')['default']
    Composables: typeof import('./src/cameras/composables/index.ts')['default']
    Mesh: typeof import('./src/objects/Mesh.ts')['default']
    MeshBasicMaterial: typeof import('./src/materials/MeshBasicMaterial.ts')['default']
    Object3D: typeof import('./src/objects/Object3D.ts')['default']
    OrbitControls: typeof import('./src/controls/OrbitControls.ts')['default']
    OrthographicCamera: typeof import('./src/cameras/OrthographicCamera.ts')['default']
    PerspectiveCamera: typeof import('./src/cameras/PerspectiveCamera.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scene: typeof import('./src/scenes/Scene.ts')['default']
    TextGeometry: typeof import('./src/geometries/TextGeometry.ts')['default']
    UseAxesHelper: typeof import('./src/helpers/composables/useAxesHelper.ts')['default']
    UseBoxGeometry: typeof import('./src/geometries/composables/useBoxGeometry.ts')['default']
    UseCamera: typeof import('./src/cameras/composables/useCamera.ts')['default']
    UseMesh: typeof import('./src/objects/composables/useMesh.ts')['default']
    UseMeshBasicMaterial: typeof import('./src/materials/composables/useMeshBasicMaterial.ts')['default']
    UseObject3D: typeof import('./src/objects/composables/useObject3D.ts')['default']
    UseOrthographicCamera: typeof import('./src/cameras/composables/useOrthographicCamera.ts')['default']
    UsePerspectiveCamera: typeof import('./src/cameras/composables/usePerspectiveCamera.ts')['default']
    UseTextGeometry: typeof import('./src/geometries/composables/useTextGeometry.ts')['default']
    UseWebGLRenderer: typeof import('./src/renderer/composables/useWebGLRenderer.ts')['default']
    WebGLRenderer: typeof import('./src/renderer/WebGLRenderer.vue')['default']
  }
}

export {}
